# @Author: David LOUISET <dlouiset>
# @Date:   2017-02-06T14:09:50+01:00
# @Last modified by:   dlouiset
# @Last modified time: 2017-03-10T11:48:59+01:00




dls_cab_user:
    resource: "@DlsCabUserBundle/Resources/config/routing.yml"
    prefix:   /

dls_cab_core:
    resource: "@DlsCabCoreBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
