# @Author: David LOUISET <dlouiset>
# @Date:   2017-03-18T15:19:59+01:00
# @Last modified by:   dlouiset
# @Last modified time: 2017-03-25T20:48:57+01:00



dls_cab_mission_index:
    path:      /{page}
    defaults:
        _controller: DlsCabMissionBundle:Affair:index
        page:        1
    requirements:
        page: \d*

dls_cab_mission_view:
    path:      /affaire/{id}
    defaults:
        _controller: DlsCabMissionBundle:Affair:view
    requirements:
        id: \d+

dls_cab_mission_new:
    path:      /new
    defaults:
        _controller: DlsCabMissionBundle:Affair:new

dls_cab_mission_edit:
    path:      /edit/{id}
    defaults:
        _controller: DlsCabMissionBundle:Affair:edit
    requirements:
        id: \d+

dls_cab_mission_delete:
    path:      /delete/{id}
    defaults:
        _controller: DlsCabMissionBundle:Affair:delete
    requirements:
        id: \d+
