<?php

namespace Dls\Bundle\CabMissionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AffairRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AffairRepository extends EntityRepository
{
}
